# Generated by Django 3.0.8 on 2020-07-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(choices=[('1', 'Budgeting'), ('2', 'Savings'), ('3', 'Investing')], max_length=150),
        ),
    ]
